In [1]:
import geopandas as gpd

In [21]:
df = gpd.read_file('./data/Counties_and_Unitary_Authorities_(December_2011)_Boundaries_EW_BGC.geojson')[['ctyua11cd','ctyua11nm','geometry']]

In [22]:
newdf = df.merge(df.bounds,left_index=True,right_index=True)

In [23]:
newdf

,ctyua11cd,ctyua11nm,geometry,minx,miny,maxx,maxy
0,E06000001,Hartlepool,"MULTIPOLYGON (((-1.27025 54.72717, -1.27251 54...",-1.383764,54.621917,-1.157724,54.727169
1,E06000002,Middlesbrough,"MULTIPOLYGON (((-1.23003 54.58411, -1.23432 54...",-1.285387,54.501125,-1.137319,54.590710
2,E06000003,Redcar and Cleveland,"MULTIPOLYGON (((-1.13718 54.64695, -1.13748 54...",-1.201743,54.487873,-0.788435,54.647583
3,E06000004,Stockton-on-Tees,"MULTIPOLYGON (((-1.31800 54.64527, -1.32071 54...",-1.452641,54.464155,-1.158829,54.645274
4,E06000005,Darlington,"POLYGON ((-1.63768 54.61714, -1.64078 54.61740...",-1.709667,54.451150,-1.407358,54.619366
...,...,...,...,...,...,...,...
169,E10000029,Suffolk,"MULTIPOLYGON (((1.68237 52.48279, 1.68140 52.4...",0.340002,51.932389,1.762942,52.550247
170,E10000030,Surrey,"POLYGON ((-0.51566 51.46827, -0.51714 51.46988...",-0.848912,51.071492,0.058243,51.471529
171,E10000031,Warwickshire,"POLYGON ((-1.57761 52.67858, -1.57943 52.67963...",-1.961966,51.955403,-1.172126,52.687261
172,E10000032,West Sussex,"MULTIPOLYGON (((-0.16693 51.16159, -0.17671 51...",-0.957581,50.722528,0.044561,51.167300
173,E10000034,Worcestershire,"POLYGON ((-2.26950 52.43862, -2.27204 52.43972...",-2.663206,51.966565,-1.757398,52.455317

In [28]:
newdf.to_file("./tiles/CountiesUA.geojson", driver="GeoJSON")

In [ ]:
# os.system('rm -rf ./tiles/tileserver/overarea; mb-util --image_format=pbf ./tiles/merged.mbtiles ./tiles/tileserver')
# os.system('cd ./tiles/tileserver && find . -type f | xargs -n1 -P 1 -t -I % gzip -d -r -S .pbf % 2>&1')
# os.system('cd ./tiles/tileserver && find . -type f | xargs -n1 -P 1 -t -I % mv % %.pbf 2>&1')